### PR TITLE
Add .travis.yml and fix doc tests

### PR DESCRIPTION
**Pull request by Marwes**
See https://github.com/rust-lang/rust/issues/49935

@freebroccolo Can you enable travis testing for this repo? (Or if you rather I fork this then I can enable it on the fork instead).

### CODE REVIEW

**Comment by freebroccolo** [comment]
Should be enabled now.

**Comment by freebroccolo** [comment]
By the way I am willing to transfer ownership of the repo to you if it makes it easier to manage. Let me know what you prefer.

**Comment by Marwes** [comment]
I'd be happy to take over ownership, were going to add that I'd like to setup status checks etc as well and stuff like that may need tweaking over time.

**Comment by Marwes** [comment]
I think for things like that it might be enough to increase the permissions on this repo though.

**Comment by freebroccolo** [comment]
I just checked but I'm not seeing a way to adjust permissions at that level. I think you can do it for an organization but I'm not sure if it's possible for an individual repo. Anyway, I tried to transfer but it tells me `marwes/pretty.rs` already exists. I think you will need to rename your fork first.

**Comment by Marwes** [comment]
Deleted my fork which should do it.

**Pull request merged**
